server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: client
          uri: http://localhost:8082
          predicates:
            - Path=/undefined/**, 
        - id: pay
          uri: http://localhost:0
          predicates:
            - Path=/undefined/**, 
        - id: store
          uri: http://localhost:0
          predicates:
            - Path=/undefined/**, 
        - id: customercenter
          uri: http://localhost:0
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: client
          uri: http://client:8080
          predicates:
            - Path=/undefined/**, 
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/undefined/**, 
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/undefined/**, 
        - id: customercenter
          uri: http://customercenter:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
